"""
Django settings for diff project.

Generated by 'django-admin startproject' using Django 1.9.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""
import os
from etcd.client import Client

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '-wyt74z-)ykjfognf%)&)o062#2pu7wi(b1ngy@m+wvw&3^#ql'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []




# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'gevent',
    'django_rq',
    'job_manager',
    'clawer',
    'parsers',
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'diff.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'diff.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DB_CONFIG_DICT = {}
client = Client(host='10.51.58.229', port=2379, allow_redirect=False)
db_config = client.read('/db', recursive=True)
for c in db_config.children:
    DB_CONFIG_DICT[c.key.split('/')[2]] = eval(c.value)

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': DB_CONFIG_DICT['question_offline_db']['db'],
        'USER': DB_CONFIG_DICT['question_offline_db']['user'],
        'PASSWORD': DB_CONFIG_DICT['question_offline_db']['passwd'],
        'HOST': DB_CONFIG_DICT['question_offline_db']['host'],
        'PORT': DB_CONFIG_DICT['question_offline_db']['port'],
    },
    'html_db': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'html_archive',
        'USER': DB_CONFIG_DICT['question_offline_db']['user'],
        'PASSWORD': DB_CONFIG_DICT['question_offline_db']['passwd'],
        'HOST': DB_CONFIG_DICT['question_offline_db']['host'],
        'PORT': DB_CONFIG_DICT['question_offline_db']['port'],
    },
    'gevent_db': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': DB_CONFIG_DICT['question_offline_db']['db'],
        'USER': DB_CONFIG_DICT['question_offline_db']['user'],
        'PASSWORD': DB_CONFIG_DICT['question_offline_db']['passwd'],
        'HOST': DB_CONFIG_DICT['question_offline_db']['host'],
        'PORT': DB_CONFIG_DICT['question_offline_db']['port'],
    },
}

DATABASE_ROUTERS = ['db_routers.routers.HtmlRouter']


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'

RQ_QUEUES = {
    'default': {
        'HOST': '10.170.251.183',
        'PORT': 16379,
        'DB': 4,
        'PASSWORD': '',
        'DEFAULT_TIMEOUT': 60,
    }
}